#!/usr/bin/env bash
# install.sh - register this ruleset with SpamAssassin without overwriting
# any existing system rules.
#
# Usage:
#   cd /etc/spamassassin
#   git clone https://github.com/oytunistrator/spamassassin-custom-list oytunistrator-custom-list
#   bash oytunistrator-custom-list/install.sh
#
# This creates a single include file (/etc/spamassassin/zz_oytun_custom_list.cf)
# which loads all .cf files from the cloned subfolder.  No existing files in
# /etc/spamassassin are modified or overwritten.

set -e

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET_DIR="/etc/spamassassin"
INCLUDE_FILE="$TARGET_DIR/zz_oytun_custom_list.cf"
REPO_NAME="$(basename "$REPO_DIR")"

if [ ! -d "$TARGET_DIR" ]; then
    echo "Error: $TARGET_DIR does not exist."
    exit 1
fi

if [ ! -w "$TARGET_DIR" ]; then
    echo "Error: $TARGET_DIR is not writable. Run as root."
    exit 1
fi

echo "Registering ruleset from $REPO_DIR"

# Create a single include file that loads all rules in alphabetical order.
{
    echo "# zz_oytun_custom_list.cf"
    echo "# Include file for $REPO_NAME"
    echo "# Generated by install.sh on $(date -Iseconds)"
    echo "#"
    echo "# This file loads the custom ruleset from the subfolder without"
    echo "# overwriting any existing SpamAssassin configuration files."
    echo ""
    for cf in "$REPO_DIR"/*.cf; do
        [ -e "$cf" ] || continue
        echo "include $cf"
    done
} > "$INCLUDE_FILE"

echo "Created: $INCLUDE_FILE"
echo ""
echo "The ruleset is now registered. It will be loaded alphabetically after"
echo "any other .cf files in $TARGET_DIR."
echo ""
echo "To disable, simply remove: $INCLUDE_FILE"
echo ""
echo "Run: spamassassin --lint"
echo "Then restart spamassassin/postfix as needed."
